### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by pfalcon** [xobs/fernly#18]
The codebase seems to lack clear license statement. Knowing that "real OS" port is based on NuttX, I hope that intention for it is to be liberally licensed (BSD/MIT), but we have that explicit, please?

**Comment by xobs** [comment]
I have removed the GPL code, and will relicense it as BSD 2-clause as requested.

**Comment by pfalcon** [comment]
Thanks! Just to clarify, I'm all for GPL, but I'd like to port another project which is BSD/MIT to MT6260, and that project is BSD/MIT because it competes with other project(s) which are BSD/MIT.
